== OCP Probe

This is a simple Python/Flask app to use in OpenShift training courses. 

The application has several version tags to create several container image
versions and demonstrate deployment strategies.

The container image registry is here: https://quay.io/repository/gpte-devops-automation/ocp-probe
Tag `v0.2`: just outputs a simple HTML with the version and hostname
Tag `v0.3`: adds the `/version` REST API call which outputs the version.
Tag `v0.4`: adds the `/hostname` REST API call.

Can be used to demonstrate load balancing with Service.
Create a ReplicaSet with 3 (or more) instances and a Service in front of them.
Create a simple Pod in the same project and call `curl ClusterIP:8080/hostname`several times.
You will see that hostnames are different.

Tag `v0.5`: adds the `/healthz` REST API call.
Can be used to demonstrate readyness checks.

YeoKH-Lab-Notes-OpenShift 4 Resources and Tools.txt
====================================================
oc login <api-server>
oc whoami --show-console

--------------------------------------------------------------------------------------------
oc adm policy add-role-to-user admin <project-manager-administrator> -n sharedproject
oc adm policy add-role-to-user edit <collaborator-developer>
oc adm policy add-role-to-user view <view-only-user>

oc adm policy remove-role-from-user edit <collaborator>
oc get rolebindings  >> List of roles for project
oc get clusterrolebindings  >> List of roles for cluster
oc describe rolebinding admin

--------------------------------------------------------------------------------------------

oc new-project ykhtest --display-name="YKH Test Project" --description="YKH Test Project"
oc project ykhtest
oc new-app --list =>  List all local templates and image streams that can be used to create an app.
oc new-app django-psql-example
oc logs -f bc/django-psql-example
oc get routes
curl <route>
oc delete all --all 
oc delete project ykhtest

--------------------------------------------------------------------------------------------

Application deployment process:
> Get image (registry, image name, tag) > Get config (ConfigMaps, secrets) > Get PV > Get resources (requests, limits)

Deployment from source:
> Get source > Get base image and build image > Store image > Get image ... as above ...

> ReplicaSet or ReplicaController is responsible for running a predefined number of pods, ensuring availability/scalability

> Deployment creates/uses ReplicaSet
> DeploymentConfig creates/users ReplicaController

Service provides stable IP address and DNS name for group of pods with floating IPs, accessible within cluster.
Route uses service to find information about pods, but DOES NOT forward traffic to service.
Route uses HAProxy to provide sophisticated load-balancing algorithms to the pods.
  "oc expose" to create route
  "oc create route" to create secured route (HTTPS).

Application Health Check:
- HTTP Checks
- Execution Checks
- TCP Socket Checks

YAML manifest components: 
  apiVersion: => Use "oc api-versions" to check applicable version to use.
  kind:       => Use "oc api-resources" to list available resource types.
  metadata:   => Define resource name, namespace, labels, annotations, ownerReferences.
  spec:       => Object/resource specifications, which may include spec of other objects/resources

oc explain pod => Provide information about the resource
oc explain pod.spec
oc explain pod.spec.namespace
oc explain pod --recursive

--------------------------------------------------------------------------------------------

oc new-project ykhproj
kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node

oc get events
oc get pods
oc get pods -o wide
oc get pods -o yaml

oc -n ykhtest get pods
oc -n ykhproj get pods

oc debug <podname> => starts a fresh pod, opening a terminal inside the pod to check/debug.
oc debug --as-root=true dc/DC-NAME
oc debug node/NODE-NAME

oc rsh <podname> => ssh into a running pod.

oc describe pod/<podname>
oc describe pod/hello-node-64c578bdf8-b5dgq
oc describe project ykhproj
Name:           ykhproj
Created:        7 hours ago
Labels:         <none>
Annotations:    openshift.io/description=
...
Resource limits:
        Name:           ykhproj-core-resource-limits
        Type            Resource        Min     Max     Default Request Default Limit   Max Limit/Request Ratio
        ----            --------        ---     ---     --------------- -------------   -----------------------
        Container       cpu             -       -       50m             500m            -
        Container       memory          10Mi    6Gi     256Mi           1536Mi          -
        Pod             memory          6Mi     12Gi    -               -               -

oc new-app --list =>  List all local templates and image streams that can be used to create an app.
oc new-app nginx-example
oc get events
oc logs -f bc/nginx-example
oc get routes
oc get pods
oc logs -f pod/nginx-example-1-build
oc logs -f pod/nginx-example-1-deploy
oc logs -f pod/nginx-example-1-n6qk8
oc rsh pod/nginx-example-1-n6qk8
oc get all

oc new-app cakephp-mysql-example 
oc get pods --field-selector status.phase=Running

oc create -f C:\DevOps\YeoKH-Notes\oc-http-dc.yaml
oc get pods --field-selector status.phase=Running -o wide --show-labels
oc create -f C:\DevOps\YeoKH-Notes\oc-http-svc.yaml
oc get service
oc create -f C:\DevOps\YeoKH-Notes\oc-http-route.yaml
oc get route

oc create -f ocp-probe-deployment.yaml
oc rollout status deployment ocp-probe
oc scale deployment ocp-probe --replicas=3
oc rollout status deployment ocp-probe
oc get pods
oc get all
oc describe rs ocp-probe-87b4cfcdd
oc describe replicaset.apps/ocp-probe-87b4cfcdd
oc describe rs/ocp-probe-87b4cfcdd

oc get deployment
oc get dc

oc edit deployment ocp-probe => Retrieve and edit a copy of deployment YAML manifest and re-deploy if changed.
oc rollout status deployment ocp-probe
   Waiting for deployment "ocp-probe" rollout to finish: 2 of 3 updated replicas are available...
   deployment "ocp-probe" successfully rolled out
oc describe deployment ocp-probe

--------------------------------------------------------------------------------------------
DEPLOYMENT

oc new-app --docker-image=quay.io/gpte-devops-automation/ocp-probe:v0.4 --name=green
oc get services
oc expose svc green --name=bluegreen
oc get routes
curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

### SWITCH BETWEEN BLUE AND GREEN ###

oc new-app --docker-image=quay.io/gpte-devops-automation/ocp-probe:v0.5 --name=blue
oc edit route bluegreen
curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

oc patch route/bluegreen -p '{"spec":{"to":{"name":"green"}}}' 
oc patch route/bluegreen -p "{\"spec\":{\"to\":{\"name\":\"green\"}}}"
curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

### A/B TESTING and CANARY DEPLOYMENT ###
oc edit route bluegreen
  to:
    kind: Service
    name: green
    weight: 50
  alternateBackends:
  - kind: Service
    name: blue
    weight: 50

LINUX$  while true; do curl $ROUTE/version ; echo ""; sleep 1; done
Window> for /L %i IN (1, 1, 10) DO curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

### CANARY DEPLOYMENT ###
oc edit route bluegreen
  alternateBackends:
  - kind: Service
    name: blue
    weight: 1
  ...
  to:
    kind: Service
    name: green
    weight: 9

Window> for /L %i IN (1, 1, 20) DO curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

oc set route-backends bluegreen blue=9 green=1
Window> for /L %i IN (1, 1, 20) DO curl bluegreen-ykhproj.apps.shared.na.openshift.opentlc.com

--------------------------------------------------------------------------------------------

References
https://kubernetes.io/docs/reference/kubectl/cheatsheet/
https://blog.openshift.com/oc-command-newbies/
https://docs.openshift.com/container-platform/4.1/cli_reference/getting-started-cli.html
https://docs.openshift.com/container-platform/4.1/cli_reference/administrator-cli-commands.html
https://docs.openshift.com/container-platform/4.1/cli_reference/developer-cli-commands.html


